app:
  name: express-sample

image:
  repository: stackdevnofil/express-sample
  tag: "1.7"

replicaCount: 1
hpa:
  replica: 
    min: 1
    max: 5

prometheus:
  prometheusSpec:
    serviceMonitorNamespaceSelector: {}

    serviceMonitorSelector:
      matchLabels:
        release: prometheus
