app:
  name: express-sample

image:
  repository: stackdevnofil/express-sample
  tag: "1.7"

replicaCount: 1
hpa:
  replica: 
    min: 1
    max: 5

prometheus:
  prometheusSpec:
    serviceMonitorNamespaceSelector: {}

    serviceMonitorSelector:
      matchLabels:
        release: prometheus

dashboard:
  enabled: true
  labels:
    grafana_dashboard: "1"
  # Set to "monitoring" if your Grafana sidecar only watches the monitoring namespace
  namespace: ""
  folder: "Applications"
