apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: express-sample

spec:
  selector:
    matchLabels:
      app: express-sample

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
